name-template: 'v$RESOLVED_VERSION 🐰'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🌈 Features'
    labels:
      - 'feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Documentation'
    label: 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: documentation
    branch:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
      - 'site/**/*'
      - 'index.html'
  - label: github
    files:
      - '.github/**/*'
  - label: site
    files:
      - 'site/**/*'
      - 'index.html'
  - label: pack
    files:
      - 'pack/**/*'
  - label: mc-model
    files:
      - 'pack/assets/minecraft/models/**/*.json'
  - label: mc-texture
    files:
      - 'pack/assets/minecraft/textures/**/*.png'
  - label: mc-sound
    files:
      - 'pack/assets/minecraft/sounds/**/*.ogg'
      - 'sounds.json'
